cms/cms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from fire import views
from fire import urls as fire_urls
from django.views.static import serve
import upload
import settings
import os
from fire import apiView
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'articles', apiView.ArticleViewSet)








urlpatterns = [
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^admin/', admin.site.urls),
    url(r'^fire/', include(fire_urls, namespace='fire')),
    url(r'^$', views.index, name='index'),

    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload.upload_image, name='upload_image'),
    url(r"^upload/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, }),


]

cms/fire/urls.py
# -*- coding: utf-8 -*-
import views

from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    # url(r'checkusername', views.check_username, name='check_username'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),

    # 用户详细信息界面
    url(r'user_detail/$', views.user_detail, name='user_detail'),
    url(r'^modify_user/$', views.modify_user, name='modify_user'),

    url(r'^(?P<article_id>[0-9]+)/comment/$', views.comment, name='commnet'),
    url(r'^(?P<article_id>[0-9]+)/keep/$', views.get_keep, name='keep'),
    url(r'^(?P<article_id>[0-9]+)/poll/$', views.get_poll_article, name='poll'),
    url(r'^(?P<article_id>[0-9]+)/$', views.article, name='article'),

    url(r'^column/(?P<column_id>[0-9]+)/$', views.get_column, name='column'),
    url(r'^search/$', views.search, name='search'),

    url(r'^create_article/$', views.create_article, name='create_article'),
    url(r'^poll_article/$',views.user_poll, name='user_poll'),
    url(r'^keep_article/$',views.user_keep, name='user_keep'),
    url(r'^comment_article/$',views.user_comment, name='user_comment'),
]

cms/fire/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
# 内置兼容python2和python3 __unicode__的装饰器，只是针对__str__方法
from django.conf import settings
from django.utils import timezone

# 用于扩展django自带的user库
from django.contrib.auth.models import AbstractBaseUser,AbstractUser


from django.contrib.auth import get_user_model
# def get_sentinel_user():
#     return get_user_model().objects.get_or_create(username='deleted')[0]

#  用户信息扩展
@python_2_unicode_compatible
class NewUser(AbstractUser):
    profile = models.CharField(verbose_name='profile',default='', max_length=256,null= True, blank=True)
    avatar = models.ImageField(verbose_name='用户头像', upload_to='user/', default='default.jpg')
    # email = models.EmailField(verbose_name='邮箱', max_length=50)


    def __str__(self):
        return self.username

# 文章所属的分类

@python_2_unicode_compatible
class Column(models.Model):
    name = models.CharField(verbose_name='column_name', max_length=256)
    intro = models.TextField(verbose_name='introduction', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = "Column"
        ordering = ['name']

# 文章管理器
class ArticleMananger(models.Manager):
    # 查询文章所属分类
    def query_by_column(self,column_id):
        query = self.get_queryset().filter(column_id=column_id)

    # 根据用户id查询文章列表
    def query_by_user(self, user_id):
        user = User.objects.get(id=user_id)
        article_list = user.article_set.all()
        return article_list

    # 根据文章点赞数排序后的文章对象
    def query_by_polls(self):
        query = self.get_queryset().order_by('poll_num')
        return query

    # 文章更新顺序获取对象，由近到远
    def query_by_time(self):
        query = self.get_queryset().order_by('-pub_date')
        return query

    # 很据文章标题模糊查询文章对象
    def query_by_keyword(self,keyword):
        query = self.get_queryset().filter(title__contains=keyword)
        return query

# self.get_queryset()   这个方法得到的是相关的查询集

#  文章数据模型
@python_2_unicode_compatible
class Article(models.Model):
    # 文章所属分类
    column = models.ForeignKey('Column',blank=True, null=True, verbose_name='belong to')
    # 标题
    title = models.CharField(max_length=256)
    # 作者
    author = models.ForeignKey('Author')
    # 收藏用户,普通用户
    user = models.ManyToManyField(NewUser, blank=True)
    # 内容
    content = models.TextField(verbose_name='content')
    # 发表时间
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    # 更新时间
    update_time = models.DateTimeField(auto_now_add=True, null=True)
    # 是否发表
    published = models.BooleanField(verbose_name='是否发表', default=True)
    # 点赞数量
    poll_num = models.IntegerField(default=0)
    # 评论数量
    comment_num = models.IntegerField(default=0)
    # 收藏数量
    keep_num = models.IntegerField(default=0)
    # 将查询类与查询方法关联起来，可以扩展其方法。objects.....
    objects = ArticleMananger()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = verbose_name = 'article'


#  评论的数据模型
@python_2_unicode_compatible
class Comment(models.Model):
    user = models.ForeignKey(NewUser, null=True)
    article = models.ForeignKey(Article, null=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    poll_num = models.IntegerField(default=0)

    def __str__(self):
        return self.content

#   增加点赞的数据模型
class Poll(models.Model):
    user = models.ForeignKey(NewUser, null=True)
    article = models.ForeignKey(Article, null=True)
    comment = models.ForeignKey(Comment, null=True)


@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=256)
    profile = models.CharField('profile',default='', max_length=256)
    password = models.CharField('password', max_length=256)
    # editable = True  强制显示
    register_date = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.name

cms/templates/article_page.html
{% extends 'index.html' %}

{% block title %}
{{ article.title }}
{% endblock %}


{% block left %}
{% endblock %}

{% block center %}

<!-- Center Column -->
<div class="col-sm-9">
	{# 文章#}
    <div class="col-xs-10 col-xs-offset-1">
	<div class="row">
		<article class="col-xs-12">
			<h2>{{ article.title }}</h2>
			<p class="pull-right">
				<span class="label label-default">{{ article.column }}</span>
				<span class="label label-default">{{ article.pub_date | date:"j M" }}</span>
				<span class="label label-default">{{ article.author }}</span>
			</p>
			<p>
				<hr>
			</p>
			<p>{{ content | safe }}</p>
			<ul class="list-inline">
				<li>
					<a href=" "><span class="glyphicon glyphicon-comme"></span> {{ article.comment_num }} 条评论</a>
				</li>
				<li>
					<a href="/fire/{{ article.id }}/keep/"><span class="glyphicon glyphicon-star-empty"></span> {{ article.keep_num }} 收藏</a>
				</li>
				<li>
					<a href="/fire/{{ article.id }}/poll/"><span class="glyphicon glyphicon-thumbs-up"></span> {{ article.poll_num }} 赞同</a>
				</li>
			</ul>
		</article>
	</div>
	<hr>
	<!--评论-->
	<h3>评论</h3>
	<hr> {% for comment in comments %}
	<div class="row">
		<article class="col-xs-12">
			<p class="pull-right"><span class="label label-default">tag</span> <span class="label-default label">{{ comment.user }}</span> </p>
			<p>{{ comment.content }}</p>

			<ul class="list-inline">
				<li>
					<a href=" ">{{ comment.pub_date | date:"j M" }}</a>
				</li>
				<li>
					<a href=" "><span class="glyphicon glyphicon-comment"></span> {{ comment.comment_num }} 评论</a>
				</li>
				<li>
					<a href=" "><span class="glyphicon glyphicon-thumbs-up"></span>{{ comment.poll_num }} 赞同</a>
				</li>
			</ul>
		</article>

	</div>
	<hr> {% endfor %} {# 评论表格#}
	<div class="row">
		<article class="col-xs-12">
			<h4>写点什么吧:</h4>
			<form action="/fire/{{ article.id }}/comment/"  method="post">
				{% csrf_token %} {{ commentform.as_p }}
				<input class="btn btn-primary" type="submit" value="提交">
			</form>
		</article>
	</div>
    </div>
</div>
	<hr>
{% endblock %}

cms/templates/base.html
<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% load staticfiles %}
    <title>{% block title %}Python World{% endblock %}</title>

    {# 预防csrf错误 #}
    {#    <script src="{% static 'csrf.js' %}"></script>#}

    <!-- Bootstrap Core CSS -->

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="{% static 'css/Pygment.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

</head>

<body>
    {% block navabar %}
        {% include 'base/nav.html' %}
    {% endblock %}

    <div class="container-fluid">

        {% block left %}

        {% endblock %}

        <!-- Center Column -->
        {% block center %}

        {% endblock %}


        {% block right %}
        <!-- Right Column -->

        {% endblock %}

    </div><!--/container-fluid-->

	<footer>
        {% block foot %}
{#            {% include 'base/foot.html' %}#}
        {% endblock %}
	</footer>



        <!-- jQuery -->
        <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- IE10 viewport bug workaround -->
        <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

        <!-- Placeholder Images -->
        <script src="{% static 'js/holder.min.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

cms/templates/column_article.html
{% extends 'index.html' %}



{% block left %}
{% endblock %}

{% block center %}

<div class="col-sm-9">
    <div class="col-xs-offset-4 col-xs-4">
        <p style="color: red">{{ msg }}</p>
    </div>
    <div class="col-xs-8 col-xs-offset-2">
    {% for article in temp_list %}
        <div class="row">
            <article class="col-xs-12">
                <h4><a id="article_title" href="/fire/{{ article.id }}">{{ article.title }}</a> </h4>
                {# 显示文章内容前80个字符，已经审核过 #}
                <p>{{ article.content | truncatechars:200 | safe }}</p>
        {#					<p><button class="btn btn-default">Read More</button></p>#}
                <p class="pull-right"><span class="label label-default">{{ article.column }}</span> <span class="label label-default">tag</span> <span class="label label-default">{{ article.author }}</span></p>
                <ul class="list-inline">
                    <li><a href="#">{{ article.pub_date | date:"j M" }}</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-comment"></span> {{ article.comment_num }} 评论</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-share"></span> {{ article.keep_num }} 分享</a></li>
                </ul>
            </article>
        </div>
        <hr>
        {% endfor %}
    </div>
        {% include 'base/cut_page.html' %}
</div>

{%  endblock %}

cms/templates/create_article.html
{%  extends 'index.html' %}
{% load staticfiles %}
{% block left %}
{% endblock %}

{% block center %}
    <div class="col-sm-9">
    <form action="" class="form col-xs-offset-2 col-xs-8" method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading" style="color: red">{{ msg }}</h2>
        <div class="form-group">
            <label>话题</label>
            <select name="column" class="form-control">
                {% for column in column_list %}
                    <option value="{{ column.id }}">{{ column.name }}</option>
                {% endfor %}
            </select>
        </div>

         <div class="form-group">
            <label>作者</label>
            <select name="author_id" class="form-control">
                {% for author in author_list %}
                    <option value="{{ author.id }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </div>

          <div class="form-group">
            <label>标题</label>
            <input name="title" type="text" class="form-control" placeholder="文章标题">
        </div>

        <div class="form-group">
            <label>文章正文</label>
            <textarea name="content"  id="id_content" class="col-xs-12" rows="100"  placeholder="文章正文"></textarea>
        </div>

{#        <div class="form-group">#}
{#            <label>作者</label>#}
{#            <input type="text" class="form-control" name="author_name" placeholder="作者昵称">#}
{#        </div>#}
{##}
{#        <div class="form-group">#}
{#            <label>简介</label>#}
{#            <input type="text" class="form-control" name="profile" placeholder="作者简介">#}
{#        </div>#}
{##}
{#        <div class="form-group">#}
{#            <label>密码</label>#}
{#            <input type="password" class="form-control" name="password1" placeholder="输入密码">#}
{#        </div>#}
{##}
{#        <div class="form-group">#}
{#            <label>重复密码</label>#}
{#            <input type="password" class="form-control" name="password2" placeholder="重复密码">#}
{#        </div>#}

        {% csrf_token %}
        <button type="submit" class="btn-danger form-control">提交</button>

    </form>
    </div>
{% endblock %}


{%  block js %}
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script src="{% static 'kindeditor/config.js' %}"></script>
{% endblock %}

cms/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}




{% block left %}
    {% include 'base/left.html' %}
{% endblock %}

<!-- Center Column -->
{% block center %}
    {% include 'base/center.html' %}
{% endblock %}


{% block right %}
<!-- Right Column -->
    {% include 'base/right.html' %}
{% endblock %}

cms/templates/login.html
{% extends 'base.html' %}
{#{% load staticfiles %}#}
{% block title %}
登录
{%  endblock %}
{% block navabar %}
{% endblock %}

{% block center %}
    <div class="row" style="background-color: deepskyblue; height: 1000px">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="row">
                <div class="col-xs-12 form center-block">
                    <form action="" class="form" method="post">
                        <h2 class="form-control-heading" style="color: red;">{{ error }}</h2>
                                {% csrf_token %}
{#                            <div class="form-group form-control">#}
                                 <label>用户名</label>
                                {{ form.uid }}
{#                            </div>#}
{#                            <div class="form-group form-control">#}
                                 <label>密码</label>
                                {{ form.pwd }}
{#                            </div>#}
                        <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>
                        <a class="btn btn-lg btn-danger btn-block" href="{% url 'fire:register' %}">注册</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{#<div id="loginModal" class="modal show">#}
{#	<div class="modal-dialog">#}
{#		<div class="modal-content">#}
{#			<div class="modal-header">#}
{#				<button type="button" class="close">x</button>#}
{#				<h1 class="text-center text-primary">登录</h1>#}
{#			</div>#}
{#			<div class="modal-body">#}
{#				<form action="" class="form col-md-12 center-block">#}
{#					<div class="form-group">#}
{#						<input type="text" class="form-control input-lg" placeholder="用户名">#}
{#					</div>#}
{#					<div class="form-group">#}
{#						<input type="password" class="form-control input-lg" placeholder="登录密码">#}
{#					</div>#}
{#					<div class="form-group">#}
{#						<button class="btn btn-primary btn-lg btn-block">立刻登录</button>#}
{#						<span><a href="#">找回密码</a></span>#}
{#						<span><a href="#" class="pull-right">注册</a></span>#}
{#					</div>#}
{#				</form>#}
{#			</div>#}
{#			<div class="modal-footer">#}
{##}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#</div>#}

{% endblock %}

{% block foot %}
{% endblock %}

cms/templates/modify_user.html
{% extends 'index.html' %}

{% block right %}
{% endblock %}

{% block center %}
    <div class="col-sm-9">
        <div class="col-xs-6 col-xs-offset-3">
            <div class="row center-block" style="background-color: rgba(33,42,162,0.74);border: 1px solid gainsboro;border-radius: 5px;">
                  <h2 class="h4 text-center">用户信息表</h2>
            </div>

            <form class="form center-block" action="" method="post" enctype="multipart/form-data">

                <img src="{{ user.avatar.url }}" style="width: 200px; height: 200px" class="img-circle img-responsive center-block">
                <label class="text-center">用户头像</label>
                <input type="file" name="avatar" class="form-control" value="{{ user.avatar }}" placeholder="请选择头像">

                <label class="text-center">用户名</label>
                <input type="text" class="form-control" name="username" value="{{ user.username }}" >

                <label class="text-center">简介</label>
                <input type="text" name="profile" height="50px" class="form-control" value="{{ user.profile }}">

                <label class="text-center">邮箱</label>
                <input type="email" name="email" value="{{ user.email }}" class="form-control">
                {% csrf_token %}
                <label> </label>
                <button type="submit" class="btn btn-danger form-control">修改</button>
            </form>

        </div>

    </div>
{% endblock %}

cms/templates/regir.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
{% load staticfiles %}
<script src="{% static "js/jquery-3.2.1.min.js" %}">
</script>
{#<script src="{% static "csrf.js" %}">#}
{#</script>#}


</head>
<body>
<h2>register page</h2>
<p>{{ msg }}</p>
<form  method="post" >
	{{ form.non_field_errors }}
	<div class="username">
	{{ form.username.errors }}
	<p> username: {{ form.username }}</p>
	</div>
	{% csrf_token %}
	<div class="email">
	{{ form.email.errors }}
	<p> email: {{ form.email }}</p>
	</div>

	<div class="password1">
	{{ form.password1.errors }}
	<p> password:</p>
	{{ form.password1 }}
	</div>

	<div class="password2">
	{{ form.password2.errors }}
	<p> repassword:</p>
	{{ form.password2 }}
	</div>
	<input id="sub" type="submit" value="Submit" >
</form>

<script>
function authentication(){
    var raw_username = document.getElementById("username").value;
{#    var csrfmiddlewaretoken = document.getElementById()#}
{#    异步处理数据#}
{#    alert($(this).val());#}
	$.ajax({type:'POST', data: {'raw_username': raw_username}
	});
};
</script>
</body>

cms/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="zh-CN">
<head>
{#    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">#}
    <meta charset="utf-8">
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">#}

    <title>用户注册</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">



</head>

<body>

<div class="container">

    <form action="{% url 'fire:register' %}" class="form-signin" method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading">{{ form.non_field_errors }}</h2>
        <h2 class="form-signin-heading" style="color: red">{{ msg }}</h2>

             <label >用户名</label>
            {{ form.username }}

            <label>头像</label>
            {{ form.avatar }}

            <label>个人简介</label>
            {{ form.profile }}

             <label>密码</label>
            {{ form.password1 }}

             <label>密码确认</label>
            {{ form.password2 }}

             <label>邮箱</label>
            {{ form.email }}
             {% csrf_token %}

{#        <label for="inputPhone">电话</label>#}
{#        <input name="phone" type="text" id="inputPhone" class="form-control" placeholder="电话">#}

        <button class="btn btn-lg btn-info btn-block" type="submit">注册</button>
    </form>

</div> <!-- /container -->
{##}
{#<script type="text/javascript">#}
{#    $(function () {#}
{#        function authentication() {#}
{#            var username = $('#username').val();#}
{#            $.get("{% url 'fire:register' %}", {raw_username:username});#}
{#            alert('ok')#}
{#        }#}
{#    })#}
{#</script>#}

</body>
</html>

cms/templates/user_action_article.html
{% extends 'index.html' %}


{% block left %}
{% endblock %}

{% block center %}

<div class="col-sm-9">
    <div class="col-xs-offset-4 col-xs-4">
        <p style="color: red">{{ msg }}</p>
    </div>
    <div class="col-xs-8 col-xs-offset-2">
    {% for action_obj in temp_list %}
        <div class="row">
            <article class="col-xs-12">
                <h4><a id="article_title" href="/fire/{{ action_obj.article.id }}">{{ action_obj.article.title }}</a> </h4>
                {# 显示文章内容前80个字符，已经审核过 #}
                <p>{{ action_obj.article.content | truncatechars:200 | safe }}</p>
        {#					<p><button class="btn btn-default">Read More</button></p>#}
                <p class="pull-right"><span class="label label-default">{{ action_obj.article.column }}</span> <span class="label label-default">tag</span> <span class="label label-default">{{ article.author }}</span></p>
                <ul class="list-inline">
                    <li><a href="#">{{ action_obj.article.pub_date | date:"j M" }}</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-comment"></span> {{ action_obj.article.comment_num }} 评论</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-share"></span> {{ action_obj.article.keep_num }} 分享</a></li>
                </ul>
            </article>
        </div>
        <hr>
        {% endfor %}
    </div>
        {% include 'base/cut_page.html' %}

</div>
{%  endblock %}

cms/templates/user_detail.html
{% extends 'index.html' %}

{% block right %}
{% endblock %}

{% block center %}
    <div class="col-sm-7 col-sm-offset-1 ">
        <div class="">
            <div class="row" style="background-color: rgba(33,42,162,0.74);border: 1px solid gainsboro;border-radius: 5px;">
                  <h2 class="h4 text-center">用户信息表</h2>
            </div>

            <img src="{{ user.avatar.url }}" style="width: 200px; height: 200px" class="img-circle img-responsive center-block">
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="badge">用户名</span>
                    {{ user.username }}
                </li>
                <li class="list-group-item">
                    <span class="badge">个人简介</span>
                    {{ user.profile }}
                </li>
                <li class="list-group-item">
                    <span class="badge">上次登录时间</span>
                    {{ user.last_login }}
                </li>
                <li class="list-group-item">
                    <span class="badge">邮箱</span>
                    {{ user.email }}
                </li>
                <li class="list-group-item">
                    <span class="badge">加入时间</span>
                    {{ user.date_joined }}
                </li>
            </ul>

            <a href="{% url 'fire:modify_user' %}"><button class="btn-danger form-control">修改个人信息</button></a>

        </div>

    </div>
{% endblock %}