cms/cms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from fire import views
from fire import urls as fire_urls
from django.views.static import serve
import upload
import settings
import os
from fire import apiView
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'articles', apiView.ArticleViewSet)








urlpatterns = [
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^admin/', admin.site.urls),
    url(r'^fire/', include(fire_urls, namespace='fire')),
    url(r'^$', views.index, name='index'),

    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload.upload_image, name='upload_image'),
    url(r"^upload/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, }),


]

cms/fire/urls.py
# -*- coding: utf-8 -*-
import views

from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    # url(r'checkusername', views.check_username, name='check_username'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),

    # 用户详细信息界面
    url(r'user_detail/$', views.user_detail, name='user_detail'),
    url(r'^modify_user/$', views.modify_user, name='modify_user'),

    url(r'^(?P<article_id>[0-9]+)/comment/$', views.comment, name='commnet'),
    url(r'^(?P<article_id>[0-9]+)/keep/$', views.get_keep, name='keep'),
    url(r'^(?P<article_id>[0-9]+)/poll/$', views.get_poll_article, name='poll'),
    url(r'^(?P<article_id>[0-9]+)/$', views.article, name='article'),

    url(r'^column/(?P<column_id>[0-9]+)/$', views.get_column, name='column'),
    url(r'^search/$', views.search, name='search'),

    url(r'^create_article/$', views.create_article, name='create_article'),
    url(r'^poll_article/$',views.user_poll, name='user_poll'),
    url(r'^keep_article/$',views.user_keep, name='user_keep'),
    url(r'^comment_article/$',views.user_comment, name='user_comment'),
]

cms/templates/base/center.html
<div class="col-sm-6">

<!-- Alert -->
{#<div class="alert alert-success alert-dismissible" role="alert">#}
{#    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>#}
{#    <strong>Synergize:</strong> Seamlessly visualize quality intellectual capital!#}
{#</div>#}

<!-- Articles -->
    {% for article in latest_article_list %}
    <div class="row">
        <article class="col-xs-12">
            <h4><a id="article_title" href="/fire/{{ article.id }}">{{ article.title }}</a> </h4>
            {# 显示文章内容前80个字符，已经审核过 #}
    {#        <p>{{ article.content|truncatechars_html:80 | safe }}</p>#}
    {#					<p><button class="btn btn-default">Read More</button></p>#}
            <p class="pull-right"><span class="label label-default">{{ article.column }}</span> <span class="label label-default">tag</span> <span class="label label-default">{{ article.author }}</span></p>
            <ul class="list-inline">
                <li><a href="#">{{ article.pub_date | date:"j M" }}</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-comment"></span> {{ article.comment_num }} 评论</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-share"></span> {{ article.keep_num }} 收藏</a></li>
            </ul>
        </article>
    </div>
    <hr>
{% endfor %}
    {% include 'base/cut_page.html'  %}
<hr>
</div><!--/Center Column-->

cms/templates/base/cut_page.html
<nav aria-label="Page navigation" class="col-xs-offset-3 col-xs-6">
	<ul class="pagination " aria-label="Page navigation">
		{% if temp_list.has_previous %}
		<li>
			<a href="?pn={{ temp_list.previous_page_number }}" aria-label=" Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in numbers %}
        {% if num == pn %}
            <li class="active "><a href="?pn={{ num }} ">{{ num }}</a></li>
         {% else %}
            <li><a href="?pn={{ num }} ">{{ num }}</a></li>
          {% endif %}
      {% endfor %}

      {% if temp_list.has_next %}
        <li>
          <a href="?pn={{ temp_list.next_page_number }}" aria-label="Next ">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
      </ul>
       <ul class="form-control" style="text-align: center">
           <li style="list-style-type: none ">当前第{% if request.GET.pn %}{{ request.GET.pn }}{% else %}{{ 1 }}{% endif %}页  总页数：{{ num_pages }}页</li>
       </ul>
        <form action=" " method="get" >
{#            <input type="hidden" value="{{ request.GET.keyword }} " name="keyword ">#}
            <input type="text" class="form-control" name="pn" placeholder="请输入跳转页数">
            <input type="submit" value="跳转" class="btn-primary form-control" >
        </form>
 </nav>

cms/templates/base/foot.html
{% load staticfiles %}
<div class="footer-blurb">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 footer-blurb-item">
                <h3><span class="glyphicon glyphicon-text-size"></span> Dynamic</h3>
                <p>Collaboratively administrate empowered markets via plug-and-play networks.
            </div>
            <div class="col-sm-3 footer-blurb-item">
                <h3><span class="glyphicon glyphicon-wrench"></span> Efficient</h3>
                <p>Dramatically maintain clicks-and-mortar solutions without functional solutions.</p>
                <p><a class="btn btn-default" href="#">Unleash</a></p>
            </div>
            <div class="col-sm-3 footer-blurb-item">
                <h3><span class="glyphicon glyphicon-paperclip"></span> Complete</h3>
                <p>Professionally cultivate one-to-one customer service with robust ideas.</p>
                <p><a class="btn btn-default" href="#">Complete</a></p>
            </div>
            <div class="col-sm-3 footer-blurb-item">

                <!-- Thumbnails -->
                <h3><span class="glyphicon glyphicon-camera"></span> Phosfluorescent</h3>
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="thumbnail">
                                <img src="{% static 'image/u=122495548,2589399830&fm=72.jpg' %}" style="width: 110px;height: 80px" alt="">
                            </a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" class="thumbnail">
                                <img src="{% static 'image/u=2595033135,3363304946&fm=27&gp=0.jpg' %}" style="width: 110px;height: 80px" alt="">
                            </a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" class="thumbnail">
                                <img src="{% static 'image/u=1765491996,2418783902&fm=27&gp=0.jpg' %}" style="width: 110px;height: 80px" alt="">
                            </a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" class="thumbnail">
                                <img src="{% static 'image/u=1142551509,1250678540&fm=27&gp=0.jpg' %}" style="width: 110px;height: 80px" alt="">
                            </a>
                        </div>
                    </div>

            </div>

        </div>
        <!-- /.row -->
    </div>
</div>
<div class="small-print">
    <div class="container">
        <p><a href="#">Terms &amp; Conditions</a> | <a href="#">Privacy Policy</a> | <a href="#">Contact</a></p>
        <p>Copyright &copy; Example.com 2015 </p>
    </div>
</div>

cms/templates/base/left.html
<!-- Left Column -->
<div class="col-sm-3">

<!-- List-Group Panel -->
<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><span class=""></span>文章分类</h1>
    </div>
    <div class="list-group">
        {% for col in column_list %}
        <a href="{% url 'fire:column' column_id=col.id %}" class="list-group-item">{{ col.name }}</a>
        {% endfor %}
    </div>
</div>

<!-- Text Panel -->
{#<div class="panel panel-default">#}
{#    <div class="panel-heading">#}
{#        <h1 class="panel-title"><span class="glyphicon glyphicon-cog"></span>页面设置</h1>#}
{#    </div>#}
{##}
{#    <div class="panel-body">#}
{#        <p>《秋风辞》#}
{#            年代: 汉 作者: 刘彻#}
{#            秋风起兮白云飞，#}
{#            草木黄落兮雁南归。#}
{#            兰有秀兮菊有芳，#}
{#            怀佳人兮不能忘。#}
{#            泛楼船兮济汾河，#}
{#            横中流兮扬素波。#}
{#            箫鼓鸣兮发棹歌，#}
{#            欢乐极兮哀情多。#}
{#            少壮几时兮奈老何！</p>#}
{#        <p><button class="btn btn-default">设置</button></p>#}
{#    </div>#}
{#</div>#}

<!-- Text Panel -->
{#<div class="panel panel-default">#}
{#    <div class="panel-heading">#}
{#        <h3 class="panel-title">#}
{#            <span class="glyphicon glyphicon-bullhorn"></span>#}
{#            每日一句#}
{#        </h3>#}
{#    </div>#}
{#    <div class="panel-body">#}
{#        <p>有志者事竟成，破釜沉舟，百二秦关终属楚；#}
{#            苦心人天不负，卧薪尝胆，三千越甲可吞吴。</p>#}
{#        <div class="btn-group" role="group">#}
{##}
{#            <button type="button" class="btn btn-default"><a href="">查看更多</a></button>#}
{##}
{#        </div>#}
{#    </div>#}
{#</div>#}

</div><!--/Left Column-->

cms/templates/base/nav.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <!-- Logo and responsive toggle -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-globe"></span>Fire</a>
        </div>
        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'fire:index' %}">首页</a>
                </li>
                <li>
                    <a href="{% url 'fire:create_article' %}">发表文章</a>
                </li>
                <li>
                    <a href="{% url 'fire:user_detail' %}">用户信息</a>

                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">用户<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="about-us">
{#                        {% url 'fire:user_detail' %}#}
{#                        <li> <a href="#">关注的人</a></li>#}
                        <li><a href="{% url 'fire:user_poll' %}">点赞的文章</a></li>
                         <li><a href="{% url 'fire:user_keep' %}">收藏的文章</a></li>
                        <li><a href="{% url 'fire:user_comment' %}">评论的文章</a></li>
                    </ul>
                </li>
            </ul>

            <!-- Search -->
            <form class="navbar-form navbar-right" action="{% url 'fire:search' %}" role="search" method="get">
                <div class="form-group">
                    {% csrf_token %}
                    <input type="text" name="search_word" class="form-control">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search</button>
            </form>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

cms/templates/base/right.html
{% load staticfiles %}
<div class="col-sm-3">


			<!-- Form -->
          {% if request.user.is_authenticated %}
          <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-log-in"></span>
                    在线
                </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                   你好：{{ user }} <a href="/fire/logout/"><button class="btn btn-default">注销</button></a>
                </div>
            </div>
        </div>
          {% else %}
          <div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<span class="glyphicon glyphicon-log-in"></span>
						登录
					</h3>
				</div>
				<div class="panel-body">
					<form action="/fire/login/" method="post">
                         {% csrf_token %}
                        {# forms.py表单自带的错误提示信息 #}
                         {{ login_form.non_field_errors }}
						<div class="form-group">
{#							<input type="text" class="form-control" id="uid" name="uid" placeholder="Username">#}
                            {{ login_form.uid }}
						</div>
						<div class="form-group">
                            {{ login_form.pwd }}
{#							<input type="password" class="form-control" id="pwd" name="pwd" placeholder="Password">#}
						</div>
                        <div class="center-block text-center">
                            <button type="submit" class="btn btn-primary">登录</button>
                            <a href="{% url 'fire:register' %}"><button class="btn btn-danger">注册</button></a>
                        </div>
					</form>

				</div>
			</div>
          {% endif %}


			<!-- Progress Bars -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<span class="glyphicon glyphicon-scale"></span>
						点赞数最高的文章
					</h3>
				</div>
				<div class="panel-body">
					<div class="progress">
						<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100"
						aria-valuemin="0" aria-valuemax="100" style="width:100%">
							100% Proactively Envisioned
						</div>
					</div>
					<div class="progress">
						<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80"
						aria-valuemin="0" aria-valuemax="100" style="width:80%">
							80% Objectively Innovated
						</div>
					</div>
					<div class="progress">
						<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="45"
						aria-valuemin="0" aria-valuemax="100" style="width:45%">
							45% Portalled
						</div>
					</div>
					<div class="progress">
						<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="35"
						aria-valuemin="0" aria-valuemax="100" style="width:35%">
							35% Done
						</div>
					</div>
				</div>
			</div>

			<!-- Carousel -->
 			<h3><span class="glyphicon glyphicon-modal-window"></span> 轻松一下</h3>
			<div id="side-carousel" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#side-carousel" data-slide-to="0" class="active"></li>
					<li data-target="#side-carousel" data-slide-to="1"></li>
					<li data-target="#side-carousel" data-slide-to="2"></li>
                    <li data-target="#side-carousel" data-slide-to="3"></li>
                    <li data-target="#side-carousel" data-slide-to="4"></li>
                    <li data-target="#side-carousel" data-slide-to="5"></li>
				</ol>
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=19752205,130612951&fm=27&gp=0.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
					<div class="item">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=122495548,2589399830&fm=72.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
					<div class="item">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=1080199734,2074924317&fm=27&gp=0.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
                    <div class="item">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=1142551509,1250678540&fm=27&gp=0.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
                    <div class="item">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=1765491996,2418783902&fm=27&gp=0.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
                      <div class="item">
						<a href="#">
							<img class="img-responsive" style="width: 400px;height: 300px" src="{% static 'image/u=2595033135,3363304946&fm=27&gp=0.jpg' %}" alt="">
						</a>
						<div class="carousel-caption">
							<h3></h3>
							<p></p>
						</div>
					</div>
				</div>
				<a class="left carousel-control" href="#side-carousel" role="button" data-slide="prev">
				  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				  <span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#side-carousel" role="button" data-slide="next">
				  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				  <span class="sr-only">Next</span>
				</a>
			  </div>

	  </div><!--/Right Column -->